media: media
content:
  - name: homePage
    type: file
    label: Home Page
    path: data/_pages/home.json
    fields:
      - name: banner
        label: Banner
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: rich-text
          - name: actionText
            label: Action Text
            type: string
          - name: actionUrl
            label: Action URL
            type: string
          - name: backgroundImage
            label: Background Image
            type: image
      - name: coreCompetencies
        label: Core Competencies
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: rich-text
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - name: heading
                label: Heading
                type: string
              - name: items
                label: Items
                type: string
                list: true
      - name: differentiators
        label: Differentiators
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: items
            label: Items
            type: object
            list: true
            fields:
              - name: icon
                label: Icon
                type: string
              - name: description
                label: Description
                type: string
  - name: aboutPage
    type: file
    label: About Page
    path: data/_pages/about.json
    fields:
      - name: heading
        label: Heading
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: rich-text
  - name: teamMembers
    label: Team Members
    type: file
    path: data/_about/teamMembers.json
    fields:
      - name: title
        label: Title
        type: string
      - name: members
        label: Members
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
          - name: position
            label: Position
            type: string
          - name: description
            label: Description
            type: rich-text
          - name: photo
            label: Photo
            type: image
            options:
              path: media/avatars
          - name: linkedinUrl
            label: LinkedIn URL
            type: string
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  - name: processPage
    type: file
    label: Process Page
    path: data/_pages/process.json
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: sections
        label: Sections
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: rich-text
          - name: items
            label: Items
            type: string
            list: true
  - name: workPage
    type: file
    label: Work Page
    path: data/_pages/work.json
    fields:
      - name: title
        label: Title
        type: string
      - name: featuredClient
        label: Featured Client
        type: object
        fields:
          - name: description
            label: Description
            type: rich-text
          - name: type
            label: Type
            type: string
      - name: footer
        label: Footer
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: rich-text
      - name: currentCategory
        label: Current Category
        type: string
      - name: categories
        label: Categories
        type: string
        list: true
  - name: work
    type: collection
    label: Work
    path: data/_work
    view:
      fields: [title, client.name, categories, isOngoing, published, date]
      sort: [date, title]
      primary: slug
      default:
        search: ''
        sort: date
        order: desc
    fields:
      - name: published
        label: Published
        type: boolean
        default: false
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: client
        label: Client
        type: string
        required: true
      - name: url
        label: URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
        required: true
      - name: date
        label: Date
        type: date
        required: true
        options:
          format: 'MM/DD/YYYY'
      - name: isOngoing
        label: Ongoing
        type: boolean
        default: false
      - name: bannerImage
        label: Banner Image
        type: image
        options:
          path: media/work/banners
          categories: [image]
      - name: description
        label: Description
        type: rich-text
      - name: categories
        label: Categories
        type: string
        list: true
      - name: problem
        label: Problem
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: image
            label: Image
            type: image
            options:
              path: media/work/problems
              categories: [image]
          - name: description
            label: Description
            type: string
      - name: solution
        label: Solution
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: image
            label: Image
            type: image
            options:
              path: media/work/solutions
              categories: [image]
          - name: description
            label: Description
            type: string
      - name: process
        label: Process
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: image
            label: Image
            type: image
            options:
              path: media/work/processes
              categories: [image]
          - name: description
            label: Description
            type: string
          - name: items
            label: Process Items
            type: object
            list: true
            fields:
              - name: imgSrc
                label: Image Source
                type: image
                options:
                  path: media/work/processes/items
                  categories: [image]
              - name: alt
                label: Alt Text
                type: string
              - name: description
                label: Description
                type: string
      - name: design
        label: Design
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: image
            label: Image
            type: image
            options:
              path: media/work/designs
              categories: [image]
          - name: description
            label: Description
            type: rich-text
          - name: items
            label: Design Items
            type: object
            list: true
            fields:
              - name: imgSrc
                label: Image Source
                type: image
                options:
                  path: media/work/designs/items
                  categories: [image]
              - name: alt
                label: Alt Text
                type: string
      - name: result
        label: Result
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: image
            label: Image
            type: image
            options:
              path: media/work/results
              categories: [image]
          - name: description
            label: Description
            type: rich-text
          - name: items
            label: Result Items
            type: object
            list: true
            fields:
              - name: imgSrc
                label: Image Source
                type: image
                options:
                  path: media/work/results/items
                  categories: [image]
              - name: alt
                label: Alt Text
                type: string
              - name: title
                label: Title
                type: string
              - name: description
                label: Description
                type: rich-text
  - name: clients
    label: Clients
    type: file
    path: data/clients.json
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: logo
        label: Logo
        type: image
        options:
          path: media/client/logos
          categories: [image]
      - name: url
        label: URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  - name: config
    label: App Config
    path: data/config.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: companyName
        label: Company Name
        type: string
      - name: description
        label: Website description
        type: rich-text
        description: Will be provided for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: address
        label: Address
        type: string
      - name: phone
        label: Phone
        type: string
      - name: email
        label: Email
        type: string
      - name: logo
        label: Logo
        type: image
        description: Image used in the header of the website.
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
      - name: naicsCodesTitle
        label: NAICS Codes Title
        type: string
      - name: naicsCodes
        label: NAICS Codes
        type: string
        list: true
      - name: companyInfo
        label: Company Info
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: value
            label: Value
            type: string
      - name: navbar
        type: object
        label: Navbar Configuration
        fields:
          - name: links
            label: Links
            type: object
            fields:
              - name: capabilities
                label: Capabilities
                type: string
              - name: startProject
                label: Start a Project
                type: string
      - name: socialLinks
        label: Social Links
        list: true
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: url
            label: URL
            type: string
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
          - name: icon
            label: Icon
            type: image
            options:
              path: media/social
              categories: [image]
      - name: style
        label: Style
        type: object
        fields:
          - name: backgroundColor
            label: Background Color
            type: string
            default: '#333'
          - name: textColor
            label: Text Color
            type: string
            default: '#fff'
      - name: footer
        label: Footer Configuration
        type: object
        fields:
          - name: footerStyle
            label: Footer Style
            type: object
            fields:
              - name: backgroundColor
                label: Background Color
                type: string
                default: '#333'
              - name: textColor
                label: Text Color
                type: string
                default: '#fff'
          - name: companyInfoStyle
            label: Company Info Style
            type: object
            fields:
              - name: backgroundColor
                label: Background Color
                type: string
                default: '#333'
              - name: textColor
                label: Text Color
                type: string
                default: '#fff'
          - name: links
            label: Links
            list: true
            type: object
            fields:
              - name: title
                label: Title
                type: string
              - name: url
                label: URL
                type: string
                pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
